// Generated by scripts/generate-route-manifest.mjs — do not edit.
// Regenerated on every `npm run build` and `npm run dev`.

/** Every static, publicly reachable page under src/app/(site). */
export const SITE_ROUTES = [
  '/',
  '/after-sales',
  '/blog',
  '/careers',
  '/company-information',
  '/contact-us',
  '/designer',
  '/faq',
  '/global-projects',
  '/privacy-policy',
  '/products/faucets',
  '/products/shower-set',
  '/products/smart-toilet',
  '/products/washstand',
  '/showroom',
  '/terms-of-use',
] as const
